# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial32"
  config.vm.provider :virtualbox do |vb|
    vb.customize [ 'modifyvm', :id, '--name', 'servidorweb' ]
    vb.customize [ 'modifyvm', :id, '--memory', '512' ]
    vb.customize [ 'modifyvm', :id, '--cpus', '2' ]
  end
  config.vm.provision "shell", path: "script.sh"
  config.vm.network "forwarded_port", guest: 80, host: 8008
  config.vm.synced_folder "html", "/var/www/html"
end
